version: "3.7"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
    networks:
      - ttw-network
  
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - acme:/etc/acme.sh
        - certs:/etc/nginx/certs
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
    environment:
    - DEFAULT_EMAIL=tom54699@gmail.com
    #encounter error when didn't add below parameter.
    - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - ttw-network

  flask:
    build: ./flask
    container_name: flask
    restart: always
    env_file: flask/api/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ttw-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    #ports:
      #- "80:80"
      #- "443:443"
    depends_on:
      - flask
    networks:
      - ttw-network
    environment:
      - VIRTUAL_HOST=taipeitrip.serveirc.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=taipeitrip.serveirc.com
      - LETSENCRYPT_EMAIL=tom54699@gmail.com

  db:
    build: ./mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1m2o3o4n
    volumes:
      - /database:/var/lib/mysql
    ports:
      - "3307:3306"  
    networks:
      - ttw-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 20
  redis:
    build: ./redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /redis:/data
    networks:
      - ttw-network

networks:
  ttw-network:

volumes:
  certs:
  vhost:
  html:
  acme: